title: "ΨΦ"
email: sidb@tempus-spatium.8shield.net
timezone: GMT
baseurl: "/psi-phi"
permalink: "/:title/"
logo: 'assets/images/site/logo.svg'
favicon: 'assets/images/site/favicon.ico'
author: Booodaness
paginate: 10
locale: en_gb
lang: en_gb
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  Booodaness:
    name: Siddhartha Bhattacharjee
    display_name: Booodaness
    avatar: 'assets/images/profiles/booodaness.png'
    email: sidb@tempus-spatium.8shield.net
    web: https://www.quora.com/profile/Siddhartha-Bhattacharjee-45
    description: "A wayfarer trying to understand the Cosmos"

# Social
social:
  discord: https://discord.com/invite/JJDMqH5

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      author: Booodaness

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
